CREATE TABLE Cliente
	( Nome VARCHAR(20) NOT NULL,
	  CPF VARCHAR(11) NOT NULL,
	  Endereco VARCHAR(40) NOT NULL,
	  ID INTEGER NOT NULL,
      PRIMARY KEY(ID));

CREATE TABLE Pedido
	( Data TIMESTAMP NOT NULL,
	  Status VARCHAR(11) NOT NULL,
	  ID INTEGER NOT NULL,
	  ID_Cliente INTEGER NOT NULL,
	  PRIMARY KEY (ID),
  FOREIGN KEY (ID_Cliente) REFERENCES Cliente(ID));

CREATE TABLE Produto
	( Nome VARCHAR(11) NOT NULL,
	  Fornecedor VARCHAR(11) NOT NULL,
	  ID INTEGER NOT NULL,
	  PRIMARY KEY (ID));

CREATE TABLE Carga
	( Origem VARCHAR(40) NOT NULL,
	  Destino VARCHAR(40) NOT NULL,
	  Entregue BOOL,
	  Descricao VARCHAR(11) NOT NULL,
	  ID INTEGER NOT NULL,
	  ID_Pedido INTEGER NOT NULL,
	  ID_Rota INTEGER NOT NULL,
	  PRIMARY KEY (ID),
  FOREIGN KEY (ID_Pedido) REFERENCES Pedido(ID),
  FOREIGN KEY (ID_Rota) REFERENCES Rota(ID));

CREATE TABLE Carga_Produto
	( ID INTEGER NOT NULL,
	  Quantidade INTEGER,
	  ID_Carga INTEGER NOT NULL,
	  ID_Produto INTEGER NOT NULL,
	  PRIMARY KEY (ID),
  	  FOREIGN KEY (ID_Carga) REFERENCES Carga(ID),
      FOREIGN KEY (ID_Produto) REFERENCES Produto(ID));

CREATE TABLE Rota
	( ID INTEGER NOT NULL,
	  ID_Veiculo VARCHAR(15) NOT NULL,
	  PRIMARY KEY (ID),
      FOREIGN KEY (ID_Veiculo) REFERENCES Veiculo(Chassi));

CREATE TABLE Veiculo
	( Chassi VARCHAR(15) NOT NULL,
	  CPF_Motorista VARCHAR(11) NOT NULL,
	  Placa VARCHAR(7) NOT NULL,
	  PRIMARY KEY (Chassi),
	  FOREIGN KEY (CPF_Motorista) REFERENCES Motorista(CPF));

CREATE TABLE Motorista
	( Nome VARCHAR(20) NOT NULL,
	  CNH VARCHAR(15) NOT NULL,
	  CPF VARCHAR(11) NOT NULL,
	  PRIMARY KEY (CPF));
